site_name: NOMAD Development Workshop
site_description: |
  Glaide Data Development Workshop for NOMAD Oasis Maintainers and Developers
site_author: Galide Data GmbH
repo_url: https://github.com/glaidedata/nomad-development-workshop-pages
edit_uri: ""

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Part 1: part-1-setup-environment.md
  - Part 2: part-2-developing-plugins.md
  - Part 3: part-3-collaborative-dev.md
  - Part 4: part-4-oasis-image.md
  - Wrap-Up & Q&A: wrap-up.md

plugins:
 - search
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/glaide_logo_long_white.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
  custom_dir: docs/theme
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://www.glaidedata.com/
  icon:
    repo: fontawesome/brands/github
  footer: |
    © FAIRmat-NFDI (Apache 2.0) — Modified by Glaide Data GmbH.
    Licensed content; redistribution prohibited without permission.
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
#  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
